-- MySQL Script generated by MySQL Workbench
-- Mon Jun 17 11:10:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 2024_oc_p6_tomtroc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `2024_oc_p6_tomtroc` ;

-- -----------------------------------------------------
-- Schema 2024_oc_p6_tomtroc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `2024_oc_p6_tomtroc` DEFAULT CHARACTER SET utf8 ;
USE `2024_oc_p6_tomtroc` ;

-- -----------------------------------------------------
-- Table `2024_oc_p6_tomtroc`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `2024_oc_p6_tomtroc`.`user` ;

CREATE TABLE IF NOT EXISTS `2024_oc_p6_tomtroc`.`user` (
                                                           `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                           `username` VARCHAR(255) NOT NULL,
                                                           `email` VARCHAR(255) NOT NULL,
                                                           `password` VARCHAR(255) NOT NULL,
                                                           `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                           `modified_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                           `thumb` VARCHAR(255) NOT NULL DEFAULT 'https://getdummyimage.com/250?size=24&extension=png',
                                                           `bday` DATETIME NOT NULL,
                                                           PRIMARY KEY (`id`));

CREATE UNIQUE INDEX `id_UNIQUE` ON `2024_oc_p6_tomtroc`.`user` (`id` ASC);

CREATE UNIQUE INDEX `email_UNIQUE` ON `2024_oc_p6_tomtroc`.`user` (`email` ASC);

CREATE UNIQUE INDEX `username_UNIQUE` ON `2024_oc_p6_tomtroc`.`user` (`username` ASC);


-- -----------------------------------------------------
-- Table `2024_oc_p6_tomtroc`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `2024_oc_p6_tomtroc`.`book` ;

CREATE TABLE IF NOT EXISTS `2024_oc_p6_tomtroc`.`book` (
                                                           `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                           `thumb` VARCHAR(255) NOT NULL,
                                                           `title` VARCHAR(255) NOT NULL,
                                                           `content` LONGTEXT NOT NULL,
                                                           `stock` INT NOT NULL DEFAULT 0,
                                                           `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                           `modified_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                           PRIMARY KEY (`id`));

CREATE UNIQUE INDEX `id_UNIQUE` ON `2024_oc_p6_tomtroc`.`book` (`id` ASC);


-- -----------------------------------------------------
-- Table `2024_oc_p6_tomtroc`.`author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `2024_oc_p6_tomtroc`.`author` ;

CREATE TABLE IF NOT EXISTS `2024_oc_p6_tomtroc`.`author` (
                                                             `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                                             `fullname` VARCHAR(255) NOT NULL,
                                                             `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                             `modified_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                             PRIMARY KEY (`id`))
    COMMENT = 'TODO Spliter fullname : first et last name';

CREATE UNIQUE INDEX `id_UNIQUE` ON `2024_oc_p6_tomtroc`.`author` (`id` ASC);


-- -----------------------------------------------------
-- Table `2024_oc_p6_tomtroc`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `2024_oc_p6_tomtroc`.`message` ;

CREATE TABLE IF NOT EXISTS `2024_oc_p6_tomtroc`.`message` (
                                                              `user_id_sender` BIGINT NOT NULL,
                                                              `user_id_recever` BIGINT NOT NULL,
                                                              `content` TEXT NOT NULL,
                                                              `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                              `modified_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                              PRIMARY KEY (`user_id_sender`, `user_id_recever`),
                                                              CONSTRAINT `fk_user_has_user_user1`
                                                                  FOREIGN KEY (`user_id_recever`)
                                                                      REFERENCES `2024_oc_p6_tomtroc`.`user` (`id`)
                                                                      ON DELETE NO ACTION
                                                                      ON UPDATE NO ACTION,
                                                              CONSTRAINT `fk_user_has_user_user2`
                                                                  FOREIGN KEY (`user_id_sender`)
                                                                      REFERENCES `2024_oc_p6_tomtroc`.`user` (`id`)
                                                                      ON DELETE NO ACTION
                                                                      ON UPDATE NO ACTION);

CREATE INDEX `fk_user_has_user_user2_idx` ON `2024_oc_p6_tomtroc`.`message` (`user_id_sender` ASC);

CREATE INDEX `fk_user_has_user_user1_idx` ON `2024_oc_p6_tomtroc`.`message` (`user_id_recever` ASC);


-- -----------------------------------------------------
-- Table `2024_oc_p6_tomtroc`.`user_has_book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `2024_oc_p6_tomtroc`.`user_has_book` ;

CREATE TABLE IF NOT EXISTS `2024_oc_p6_tomtroc`.`user_has_book` (
                                                                    `user_id` BIGINT NOT NULL,
                                                                    `book_id` INT UNSIGNED NOT NULL,
                                                                    PRIMARY KEY (`user_id`, `book_id`),
                                                                    CONSTRAINT `fk_user_has_book_user1`
                                                                        FOREIGN KEY (`user_id`)
                                                                            REFERENCES `2024_oc_p6_tomtroc`.`user` (`id`)
                                                                            ON DELETE NO ACTION
                                                                            ON UPDATE NO ACTION,
                                                                    CONSTRAINT `fk_user_has_book_book1`
                                                                        FOREIGN KEY (`book_id`)
                                                                            REFERENCES `2024_oc_p6_tomtroc`.`book` (`id`)
                                                                            ON DELETE NO ACTION
                                                                            ON UPDATE NO ACTION);

CREATE INDEX `fk_user_has_book_book1_idx` ON `2024_oc_p6_tomtroc`.`user_has_book` (`book_id` ASC);

CREATE INDEX `fk_user_has_book_user1_idx` ON `2024_oc_p6_tomtroc`.`user_has_book` (`user_id` ASC);


-- -----------------------------------------------------
-- Table `2024_oc_p6_tomtroc`.`book_has_author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `2024_oc_p6_tomtroc`.`book_has_author` ;

CREATE TABLE IF NOT EXISTS `2024_oc_p6_tomtroc`.`book_has_author` (
                                                                      `book_id` INT UNSIGNED NOT NULL,
                                                                      `author_id` INT UNSIGNED NOT NULL,
                                                                      PRIMARY KEY (`book_id`, `author_id`),
                                                                      CONSTRAINT `fk_book_has_author_book1`
                                                                          FOREIGN KEY (`book_id`)
                                                                              REFERENCES `2024_oc_p6_tomtroc`.`book` (`id`)
                                                                              ON DELETE NO ACTION
                                                                              ON UPDATE NO ACTION,
                                                                      CONSTRAINT `fk_book_has_author_author1`
                                                                          FOREIGN KEY (`author_id`)
                                                                              REFERENCES `2024_oc_p6_tomtroc`.`author` (`id`)
                                                                              ON DELETE NO ACTION
                                                                              ON UPDATE NO ACTION);

CREATE INDEX `fk_book_has_author_author1_idx` ON `2024_oc_p6_tomtroc`.`book_has_author` (`author_id` ASC);

CREATE INDEX `fk_book_has_author_book1_idx` ON `2024_oc_p6_tomtroc`.`book_has_author` (`book_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;