USE `2024_oc_p6_tomtroc` ;
insert into user_has_book (book_id, user_id, stock) values (7, 19, 0);
insert into user_has_book (book_id, user_id, stock) values (8, 18, 0);
insert into user_has_book (book_id, user_id, stock) values (15, 8, 0);
insert into user_has_book (book_id, user_id, stock) values (16, 10, 1);
insert into user_has_book (book_id, user_id, stock) values (14, 13, 3);
insert into user_has_book (book_id, user_id, stock) values (6, 13, 7);
insert into user_has_book (book_id, user_id, stock) values (9, 1, 2);
insert into user_has_book (book_id, user_id, stock) values (11, 5, 0);
insert into user_has_book (book_id, user_id, stock) values (3, 15, 2);
insert into user_has_book (book_id, user_id, stock) values (13, 9, 0);
insert into user_has_book (book_id, user_id, stock) values (19, 1, 1);
insert into user_has_book (book_id, user_id, stock) values (4, 2, 2);
insert into user_has_book (book_id, user_id, stock) values (19, 3, 1);
insert into user_has_book (book_id, user_id, stock) values (5, 15, 7);
insert into user_has_book (book_id, user_id, stock) values (8, 11, 0);
insert into user_has_book (book_id, user_id, stock) values (3, 5, 0);
insert into user_has_book (book_id, user_id, stock) values (18, 19, 8);
insert into user_has_book (book_id, user_id, stock) values (17, 13, 1);
insert into user_has_book (book_id, user_id, stock) values (17, 19, 1);
insert into user_has_book (book_id, user_id, stock) values (6, 6, 6);
insert into user_has_book (book_id, user_id, stock) values (13, 2, 1);
insert into user_has_book (book_id, user_id, stock) values (10, 7, 0);
insert into user_has_book (book_id, user_id, stock) values (10, 12, 5);
insert into user_has_book (book_id, user_id, stock) values (20, 1, 0);
insert into user_has_book (book_id, user_id, stock) values (5, 17, 9);
insert into user_has_book (book_id, user_id, stock) values (6, 14, 0);
insert into user_has_book (book_id, user_id, stock) values (10, 11, 1);
insert into user_has_book (book_id, user_id, stock) values (2, 17, 1);
insert into user_has_book (book_id, user_id, stock) values (19, 9, 2);
insert into user_has_book (book_id, user_id, stock) values (19, 18, 0);
insert into user_has_book (book_id, user_id, stock) values (16, 13, 2);
insert into user_has_book (book_id, user_id, stock) values (12, 13, 2);
insert into user_has_book (book_id, user_id, stock) values (19, 13, 1);
insert into user_has_book (book_id, user_id, stock) values (4, 16, 1);
insert into user_has_book (book_id, user_id, stock) values (20, 6, 0);
insert into user_has_book (book_id, user_id, stock) values (14, 20, 0);
insert into user_has_book (book_id, user_id, stock) values (14, 7,10);
insert into user_has_book (book_id, user_id, stock) values (4, 5, 0);
insert into user_has_book (book_id, user_id, stock) values (9, 17, 1);
insert into user_has_book (book_id, user_id, stock) values (11, 8, 0);
insert into user_has_book (book_id, user_id, stock) values (11, 6, 3);
insert into user_has_book (book_id, user_id, stock) values (8, 19, 0);
insert into user_has_book (book_id, user_id, stock) values (18, 5, 0);
insert into user_has_book (book_id, user_id, stock) values (6, 16, 2);
insert into user_has_book (book_id, user_id, stock) values (2, 3, 0);
insert into user_has_book (book_id, user_id, stock) values (11, 11, 0);
insert into user_has_book (book_id, user_id, stock) values (4, 15, 1);
insert into user_has_book (book_id, user_id, stock) values (13, 7, 0);
insert into user_has_book (book_id, user_id, stock) values (6, 10, 0);
insert into user_has_book (book_id, user_id, stock) values (1, 4, 1);
insert into user_has_book (book_id, user_id, stock)
values (11, 17, 2);
insert into user_has_book (book_id, user_id, stock)
values (4, 17, 0);
insert into user_has_book (book_id, user_id, stock)
values (13, 17, 1);
insert into user_has_book (book_id, user_id, stock)
values (6, 17, 0);
insert into user_has_book (book_id, user_id, stock)
values (1, 17, 1);
